import {useEffect,useState} from 'react';
import {ArrowLeft,Download,HardDrive,LockKeyhole,RefreshCw,ShieldCheck,Upload} from 'lucide-react';
import {TouchField,TouchInputProvider} from './TouchField';
import {setupTheme} from './setupTheme';
import {applyGameCheckpoints,readGameCheckpoints} from './gameCheckpoint';
import {announceAdminNeeded} from './adminState';

type Backup={id:string;created_at:string};
type Volume={id:string;label:string;backups:Backup[]};
type Preview={preview_id:string;expires_in_seconds:number;created_at:string;theme:string;orientation:string;counts:Record<string,number>;preserved_here:string[];requires_review:string[]};

export function BackupSetup({demo=false,locked=false,onSaved}:{demo?:boolean;locked?:boolean;onSaved?:()=>void}){
  const [theme]=useState(()=>setupTheme(new URLSearchParams(location.search).get('theme')));
  const [volumes,setVolumes]=useState<Volume[]>([]),[volume,setVolume]=useState(''),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[phase,setPhase]=useState<'choose'|'export'|'import'|'review'>('choose');
  const [passphrase,setPassphrase]=useState(''),[confirmation,setConfirmation]=useState(''),[preview,setPreview]=useState<Preview|null>(null);
  const selected=volumes.find(item=>item.id===volume);
  useEffect(()=>{if(!demo)void scan();},[]);
  async function call<T>(url:string,body?:unknown):Promise<T>{const response=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await response.json().catch(()=>({}));if(!response.ok){announceAdminNeeded(data);throw Error(data.detail||'Luma could not complete that backup step.');}return data as T;}
  async function scan(){setLoading(true);setMessage('');try{const result=demo?{volumes:[{id:'demo-drive',label:'USB backup drive',backups:[{id:'demo-backup',created_at:new Date().toISOString()}]}]}:await call<{volumes:Volume[]}>('/api/v1/backups/scan',{});setVolumes(result.volumes);setVolume(current=>result.volumes.some(item=>item.id===current)?current:result.volumes[0]?.id||'');setMessage(result.volumes.length?'USB drive ready.':'Connect a writable USB drive, then scan again.');}catch(error){setMessage((error as Error).message);}finally{setLoading(false);}}
  async function exportSettings(event:React.FormEvent){event.preventDefault();if(!selected)return;if(passphrase.length<12){setMessage('Use a passphrase with at least 12 characters.');return;}if(passphrase!==confirmation){setMessage('The passphrases do not match.');return;}setLoading(true);setMessage('');try{const games=demo?{}:readGameCheckpoints();if(demo){setMessage('Preview only — no file was written.');}else{const result=await call<{verified:boolean}>('/api/v1/backups/export',{volume_id:volume,passphrase,confirm_passphrase:confirmation,games});setMessage(result.verified?'Encrypted settings and saved game runs are verified on the USB drive.':'Luma could not verify the backup.');await scan();onSaved?.();}}catch(error){setMessage((error as Error).message);}finally{setPassphrase('');setConfirmation('');setLoading(false);}}
  async function openBackup(id:string){if(!selected)return;if(passphrase.length<12){setMessage('Enter the backup passphrase (12 characters or more).');return;}setLoading(true);setMessage('');try{const result=demo?{preview_id:'demo-preview',expires_in_seconds:300,created_at:new Date().toISOString(),theme:'hearth',orientation:'landscape',counts:{countdowns:0,transit_favorites:0,scene_intents:0,game_checkpoints:0},preserved_here:['Google account and calendar links','phone pairing','PIN and privacy state','purifier binding and credentials',"this Pi's current microphone mute"],requires_review:['Google and phone links are not transferred','restored scenes stay off until rebound']}:await call<Preview>('/api/v1/backups/preview',{volume_id:volume,backup_id:id,passphrase});setPreview(result);setPhase('review');setMessage('Review the restore carefully. Nothing has changed yet.');}catch(error){setMessage((error as Error).message);}finally{setPassphrase('');setLoading(false);}}
  async function restore(){if(!preview)return;setLoading(true);setMessage('');try{if(demo){setMessage('Preview only — no settings were changed.');}else{const result=await call<{games:unknown}>('/api/v1/backups/apply',{preview_id:preview.preview_id,confirmed:true});try{applyGameCheckpoints(result.games);}catch{setMessage('Settings restored, but the saved game runs could not be copied into this browser. The current game saves were kept.');setPreview(null);setPhase('choose');await scan();return;}setMessage('Settings and validated game runs restored. Reconnect calendar and phone links as needed.');setPreview(null);setPhase('choose');await scan();onSaved?.();}}catch(error){setMessage((error as Error).message);}finally{setLoading(false);}}
  async function eject(){if(!selected)return;setLoading(true);setMessage('');try{if(!demo)await call('/api/v1/backups/eject',{volume_id:volume});setVolumes([]);setVolume('');setPhase('choose');setMessage(demo?'Preview only — drive stays connected.':'Drive safely ejected.');}catch(error){setMessage((error as Error).message);}finally{setLoading(false);}}
  const disabled=loading||locked;
  return <TouchInputProvider><section className={`portable-backup theme-${theme}`} aria-labelledby="portable-backup-title">
    <button disabled={disabled} className="backup-back" onClick={()=>{setPhase('choose');setPreview(null);setMessage('')}}><ArrowLeft aria-hidden="true"/> Extras</button>
    <h2 id="portable-backup-title"><HardDrive aria-hidden="true"/> Settings backup</h2>
    <p>Encrypted, portable settings only. Your Google links, phone pairing and device credentials stay on this hub.</p>
    {locked&&<p role="status">Unlock Luma with your nearby phone or PIN before using backups.</p>}
    <div className="backup-drive-row"><strong>{selected?.label||'No USB drive selected'}</strong><button disabled={disabled} onClick={()=>void scan()}><RefreshCw aria-hidden="true"/>{loading?'Checking…':'Scan USB'}</button></div>
    {volumes.length>1&&<label>USB drive<select disabled={disabled} value={volume} onChange={event=>setVolume(event.target.value)}>{volumes.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>}
    {phase==='choose'&&<div className="backup-actions"><button disabled={disabled||!selected} onClick={()=>{setPhase('export');setMessage('')}}><Download aria-hidden="true"/>Save settings</button><button disabled={disabled||!selected||!selected.backups.length} onClick={()=>{setPhase('import');setMessage('')}}><Upload aria-hidden="true"/>Restore settings</button></div>}
    {phase==='export'&&<form onSubmit={event=>void exportSettings(event)}><h3>Protect the backup</h3><p>Choose a passphrase you can keep safe. Luma cannot recover it. Use the same phrase if you restore this file later.</p><TouchField label="Backup passphrase" secret value={passphrase} onChange={setPassphrase} minLength={12} maxLength={128} required disabled={disabled}/><TouchField label="Repeat passphrase" secret value={confirmation} onChange={setConfirmation} minLength={12} maxLength={128} required disabled={disabled}/><div className="backup-actions"><button type="button" disabled={disabled} onClick={()=>setPhase('choose')}>Cancel</button><button disabled={disabled}><LockKeyhole aria-hidden="true"/>{loading?'Saving securely…':'Encrypt & save'}</button></div></form>}
    {phase==='import'&&<><h3>Choose a saved backup</h3>{selected?.backups.map(item=><button className="backup-file" disabled={disabled} key={item.id} onClick={()=>void openBackup(item.id)}><span>{new Date(item.created_at).toLocaleString()}</span><strong>Review restore →</strong></button>)}<TouchField label="Backup passphrase" secret value={passphrase} onChange={setPassphrase} minLength={12} maxLength={128} required disabled={disabled}/><p className="backup-note">Select a file above after entering its passphrase. Restores are previewed before anything changes.</p><button disabled={disabled} onClick={()=>setPhase('choose')}>Cancel</button></>}
    {phase==='review'&&preview&&<div className="backup-review"><h3><ShieldCheck aria-hidden="true"/>Review before restoring</h3><p>Backup date: {new Date(preview.created_at).toLocaleString()} · {preview.theme} · {preview.orientation}</p><dl>{Object.entries(preview.counts).map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{value}</dd></div>)}</dl><h4>Stays on this Luma</h4><ul>{preview.preserved_here.map(item=><li key={item}>{item}</li>)}</ul><h4>Needs review after restore</h4><ul>{preview.requires_review.map(item=><li key={item}>{item}</li>)}</ul><p className="backup-note">Restored scenes remain disabled until you review and reconnect them. Current Google credentials, calendar IDs, phone identity, appliance bindings, PIN and microphone mute are preserved. Saved game runs from this backup replace only the matching local games.</p><div className="backup-actions"><button disabled={disabled} onClick={()=>{setPreview(null);setPhase('choose');}}>Cancel</button><button disabled={disabled} onClick={()=>void restore()}>{loading?'Restoring…':'Confirm restore'}</button></div></div>}
    {!demo&&selected&&<button className="backup-eject" disabled={disabled} onClick={()=>void eject()}>Safely eject USB</button>}
    {message&&<p className="setup-message" role="status">{message}</p>}
    <p className="backup-note">The archive is encrypted with AES-GCM. Never save the passphrase beside the USB drive. This does not export accounts, calendar data, voice recordings or cached events.</p>
  </section></TouchInputProvider>;
}
