context.modules = [
  { name = libpipewire-module-echo-cancel
    args = {
      library.name = aec/libspa-aec-webrtc
      node.latency = 1024/48000
      audio.channels = 1
      audio.position = [ MONO ]
      source.props = {
        node.name = "luma_mic"
        node.description = "Luma Echo-Cancelled Microphone"
      }
      sink.props = {
        node.name = "luma_speaker"
        node.description = "Luma Speaker"
      }
      aec.args = {
        webrtc.extended_filter = true
        webrtc.delay_agnostic = true
        webrtc.noise_suppression = true
        webrtc.gain_control = true
        webrtc.voice_detection = true
      }
    }
  }
]
